verify os parameters

diff --git a/create-glazier b/create-glazier
--- a/create-glazier
+++ b/create-glazier
@@ -2,7 +2,7 @@
 
 
 # defaults. They can be overwritten by command line parameters
-verbosity=3  # 1=least verbose, 3=most verbose
+verbosity=2  # 1=least verbose, 3=most verbose
 dry_run="no"
 vmname="glaziervm"
 vmpath="~/.glazier"
@@ -97,7 +97,61 @@ function set_colors()
 	fi
 }
 
+function check_os() 
+{
+	auth_request "tenantId" $OS_TENANT_ID
+	auth_request "tenantName" $OS_TENANT_NAME 
+}
 
+#verifies if provided OpenStack credentials are valid
+function auth_request()
+{
+	info 2 "Checking OpenStack credentials for ${1} ${2}"
+	local request="
+{ \"auth\":
+   {
+        \"$1\": \"$2\",
+        \"passwordCredentials\": {
+            \"username\": \"$OS_USERNAME\",
+            \"password\": \"$OS_PASSWORD\"
+        }
+    }
+
+}"
+	local curl_verbosity=""
+	if [ $verbosity -lt 3 ];
+	then
+		curl_verbosity='-sS' 
+	fi
+
+	local ignnore_ssl=""
+        if [ "$insecure" == "true"  ];
+	then
+		ignore_ssl="--insecure"
+	fi
+
+	local cacert=""
+	if [ ! -z "${OS_CACERT}" ];
+	then
+		cacert="--cacert ${OS_CACERT}"
+	fi
+
+        local curl_output=`curl -X POST -w "%{http_code}" $ignore_ssl ${cacert} -i -H "Content-type: application/json" -d "$request" ${OS_AUTH_URL}/tokens $curl_verbosity`
+	if [ $verbosity -eq 3 ];
+        then
+                echo $curl_output
+        fi
+
+	curl_code=`echo $curl_output | rev | cut -b 1-3 | rev`
+
+	if [ $curl_code -ne 200 ];
+	then
+		error 1 "Unable to validate OpenStack credentials for ${1}: $2"
+		exit 1
+	fi
+
+	info 2 "Successfully validated credentials for ${1} ${2}"
+}
 
 # checks what operating system this is
 function get_os()
@@ -1038,7 +1092,6 @@ function map_drive_letters()
 }
 
 
-
 # create the temporary directory if it doesent exist
 if [ ! -d ${tmpdir} ];
 then
@@ -1053,6 +1106,7 @@ set_colors
 validate_environment_vars
 validate_net_connectivity
 validate_prerequisites
+check_os
 validate_profiles
 create_vfd
 run_virtualbox
