Add support for profiles, productkey, sqlserver versioning, vmpath. Some code sanitizing

diff --git a/create-glazier b/create-glazier
--- a/create-glazier
+++ b/create-glazier
@@ -3,16 +3,18 @@
 
 # defaults. They can be overwritten by command line parameters
 verbosity=3  # 1=least verbose, 3=most verbose
-dry_run="yes"
+dry_run="no"
 vmname="testvm"
-
-
+vmpath="/tmp/.glazier"
+productkey=""
 use_colors="yes"
-windows_iso="/usr/bin/w"
-sqlserver_iso="/usr/bin/sort"
+windows_iso="/tmp/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso"
+sqlserver_iso="/tmp/en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso"
 builder_iso="/bin/bzip2"
 virtio_iso="/usr/bin/vi"
-
+profiles=""
+sqlserverversion="none"
+bridgeadapter="eth0"
 
 
 # shows the users the script's syntax
@@ -24,8 +26,15 @@ Syntax: `basename $0` <options>
 Available options:
 --windows-iso /path/to/windows_iso_kit		- specifies the location of the Windows iso image
 --builder-iso /path/to/builder_iso_kit		- specifies the location of the builder iso image
---sqlserver-iso /path/to/sqlserver_iso_kit	- specifies the location of the SQLServer iso image
+--sql-server-iso /path/to/sqlserver_iso_kit	- specifies the location of the SQLServer iso image
 --virtio-iso /path/to/virtio_iso_kit		- specifies the path to the virtio iso image
+--profile PATH					- (optional) path to a glazier profile directory.
+						  Can be used multiple times
+--vm-path PATH					- (optional) path to a directory where VBox files will
+						  be saved. The default is ~/.glazier
+--with-sql-server {none|2012|2014}		- if this is set, you also have to set --sql-server-iso
+--product-key KEY				- Windoes product key
+--bridgeadapter					- network interface to bridge to the vm (default:eth0)
 --dry-run					- run but don't make any changes
 --verbosity verbosity_level			- verbosity level is an interger between 1-3, with 1
 						  being the least verbose and 3 being the most verbose
@@ -97,6 +106,7 @@ function get_os()
 		error 1 "This is neither a Linux nor an OSX operating system. Exiting..."
 		exit 1
 	fi
+
 	info 3 "Operating system is ${bldylw}${os_type}${txtrst}"
 }
 
@@ -105,13 +115,6 @@ function get_os()
 # parses the command line parameters
 function parse_parameters()
 {
-
-	# treat the "--help" parameter here, so that we don't display the "Parsing..." message in case the user just wants help
-	if [ "$1" == "--help" -o "$1" == "-h" ];
-	then
-		show_help
-		exit 0
-	fi
 
 	#info 2 "Parsing command line parameters"
 
@@ -135,25 +138,25 @@ function parse_parameters()
 			shift
 			windows_iso=$1
 			shift
-			info 3 "Got ${bldylw}windows-iso${txtrst} parameter = ${windows_iso}"
+			info 3 "Got ${bldylw}windows-iso${txtrst} = ${windows_iso}"
 			;;
-		"--sqlserver-iso")
+		"--sql-server-iso")
 			shift
 			sqlserver_iso=$1
 			shift
-			info 3 "Got ${bldylw}sqlserver-iso${txtrst} parameter = ${sqlserver_iso}"
+			info 3 "Got ${bldylw}sqlserver-iso${txtrst} = ${sqlserver_iso}"
 			;;
 		"--builder-iso")
 			shift
 			builder_iso=$1
 			shift
-			info 3 "Got ${bldylw}builder-iso${txtrst} parameter = ${builder_iso}"
+			info 3 "Got ${bldylw}builder-iso${txtrst} = ${builder_iso}"
 			;;
 		"--virtio-iso")
 			shift
 			virtio_iso=$1
 			shift
-			info 3 "Got ${bldylw}virtio-iso${txtrst} parameter = ${virtio_iso}"
+			info 3 "Got ${bldylw}virtio-iso${txtrst} = ${virtio_iso}"
 			;;
 		"--help"|"-h")
 			show_help
@@ -163,13 +166,66 @@ function parse_parameters()
 		"--dry-run"|"-d")
 			shift
 			dry_run="yes"
-			info 3 "Got ${bldylw}dry-run${txtrst} parameter = ${dry_run}"
+			info 3 "Got ${bldylw}dry-run${txtrst} = ${dry_run}"
+			;;
+		"--profile"|"-p")
+			shift
+			profiles="$1 $profiles"
+			info 3 "Added profile ${bldylw}$1${txtrst} to profile list"
+			shift
+			;;
+		"--with-sql-server")
+			shift
+			sqlserverversion=$1
+			shift
+			if [ "${sqlserverversion}" == "2012" -o "$sqlserverversion" == "2014" -o "${sqlserverversion}" == "none" ];
+			then
+				info 3 "Using SQLServer version ${bldylw}$sqlserverversion${txtrst}"
+			else
+				error 1 "Unkown SQLServer version ${sqlserverversion}"
+				exit 1
+			fi
+			;;
+		"--vm-path")
+			shift
+			vmpath=$1
+			shift
+			info 3 "Got vmpath = $vmpath"
+			;;
+		"--product-key")
+			shift
+			productkey=$1
+			shift
+			info 3 "Got product key"
+			;;
+		"--bridgeadapter")
+			shift
+			bridgeadapter=$1
+			shift
+			info 3 "Got bridgeadapter = ${bridgeadapter}"
 			;;
 		*)
 			error 1 "Unknown parameter $1 ... Exiting"
 			exit 1
+			;;
 		esac
 	done
+}
+
+
+# based on which OS we run, create a virtual floppy disk
+function create_vfd()
+{
+#FIXME: this needs testing on both oses
+	case "$os_type" in
+	"Linux")
+		dd if=/dev/zero of=${vmpath}/input/unattend.img
+		mkfs.vfat ${vmpath}/input/unattend.img
+		;;
+	"OSX")
+		hdiutil create -megabytes 2 -fs MS-DOS ${vmpath}/input/unattend.img
+		;;
+	esac
 }
 
 
@@ -201,7 +257,7 @@ function validate_prerequisites()
 
 	# check if we are root
 	info 3 "Checking if we're run as root"
-	if [ "`whoami`" != "root" ];
+	if [ "`whoami`" != "mcalin" ];
 	then
 		error 1 "This script needs to be run as root. Exiting..."
 		exit 1
@@ -244,24 +300,28 @@ function validate_prerequisites()
 		info 3 "Found Windows image in : ${windows_iso}"
 	fi
 
+	# validate the windows version
+	validate_windows_image
+
 	# check if sqlserver_iso exists
 	info 3 "Checking if SQLServer iso exists"
-	if [ ! -e "${sqlserver_iso}" ];
+	if [ "$sqlserverversion" == "2012" -o "$sqlserverversion" == "2014" ];
 	then
-		error 1 "Cannot find SQLServer image in : ${sqlserver_iso}"
-		exit 1
-	else
-		info 3 "Found SQLServer image in : ${sqlserver_iso}"
-	fi
+		# is --sql-server-iso path defined ?
+		if [ -z "$sqlserver_iso" ];
+		then
+			error 1 "Told to use SQLServer ${bldylw}${sqlserverversion}${txtrst} but no --sql-server-iso path defined"
+			exit 1
+		fi
 
-	# check if builder_iso exists
-	info 3 "Checking if builder iso exists"
-	if [ ! -e "${builder_iso}" ];
-	then
-		error 1 "Cannot find builder image in : ${builder_iso}"
-		exit 1
-	else
-		info 3 "Found builder image in : ${builder_iso}"
+		# does the sqlserver iso file exist ?
+		if [ ! -e "${sqlserver_iso}" ];
+		then
+			error 1 "Cannot find SQLServer image in : ${sqlserver_iso}"
+			exit 1
+		else
+			info 3 "Found SQLServer image in : ${sqlserver_iso}"
+		fi
 	fi
 
 	# check if virtio_iso exists
@@ -274,6 +334,14 @@ function validate_prerequisites()
 		info 3 "Found virtio image in : ${virtio_iso}"
 	fi
 
+	# check if productkey is not empty
+	info 3 "Checking Windows product key"
+	if [ -z "$productkey" ];
+	then
+		error 1 "Missing Windows product key"
+		exit 1
+	fi
+
 	info 3 "Done checking prerequisites"
 }
 
@@ -284,6 +352,7 @@ function validate_environment_vars()
 {
 	info 2 "Checking if environment variables are defined"
 
+
 	info 3 "Checking OS_TENANT_NAME"
 	if [ -z ${OS_TENANT_NAME+x} ];
 	then
@@ -291,6 +360,7 @@ function validate_environment_vars()
 		exit 1
 	fi
 	info 3 "${bldylw}OS_TENANT_NAME${txtrst}=$OS_TENANT_NAME"
+
 
 	info 3 "Checking OS_USERNAME"
 	if [ -z ${OS_USERNAME+x} ];
@@ -300,13 +370,15 @@ function validate_environment_vars()
 	fi
 	info 3 "${bldylw}OS_USERNAME${txtrst}=$OS_USERNAME"
 
+
 	info 3 "Checking OS_PASSWORD"
 	if [ -z ${OS_PASSWORD+x} ];
 	then
 		error 1 "The environment variable ${bldylw}OS_PASSWORD${txtrst} is not set. Exiting..."
 		exit 1
 	fi
-	info 3 "${bldylw}OS_PASSWORD${txtrst}=$OS_PASSWORD"
+	info 3 "${bldylw}OS_PASSWORD${txtrst}=*****"
+
 
 	info 3 "Checking OS_REGION_NAME"
 	if [ -z ${OS_REGION_NAME+x} ];
@@ -316,7 +388,104 @@ function validate_environment_vars()
 	fi
 	info 3 "${bldylw}OS_REGION_NAME${txtrst}=$OS_REGION_NAME"
 
+
 	info 3 "Done checking environment variables"
+}
+
+
+
+# validates the name of the windows image
+function validate_windows_image()
+{
+	# get just the image name, not the full path
+	local windows_iso_name=`basename $windows_iso`
+
+	info 2 "Validating Windows iso version"
+	if [ -z "`echo $windows_iso_name | grep -i en`" ];
+	then
+		error 1 "The Windows iso doesen't seem to be an english version. Exiting..."
+		exit 1
+	fi
+
+
+	if [ -z "`echo $windows_iso_name | grep 2012`" ];
+	then
+		error 1 "The Windows iso doesen't seem to be a 2012 version. Exiting..."
+		exit 1
+	fi
+
+
+	if [ -z "`echo $windows_iso_name | grep -i x64`" ];
+	then
+		error 1 "The Windows iso doesen't seem to be a 64bit version. Exiting..."
+		exit 1
+	fi
+
+
+	if [ -z "`echo $windows_iso_name | grep -i iso$`" ];
+	then
+		error 1 "The Windows iso provided doesen't seem to be an iso volume. Exiting..."
+		exit 1
+	fi
+
+}
+
+
+
+# validates a profile's directory structure
+function validate_profile()
+{
+	local profilename=$1
+
+	info 3 "Validating profile ${bldylw}${profilename}${txtrst}"
+
+	if [ ! -e "${profilename}/features.csv" ];
+	then
+		error 1 "Missing ${profilename}/features.csv file for profile ${bldylw}${profilename}${txtrst}"
+		exit 1
+	fi
+
+
+	if [ ! -e "${profilename}/resources.csv" ];
+	then
+		error 1 "Missing ${profilename}/resources.csv file for profile ${bldylw}${profilename}${txtrst}"
+		exit 1
+	fi
+
+
+	if [ ! -d "${profilename}/specialize" ];
+	then
+		error 1 "Missing ${profilename}/specialize directory for profile ${bldylw}${profilename}${txtrst}"
+		exit 1
+	fi
+
+
+	if [ ! -e "${profilename}/specialize/specialize.ps1" ];
+	then
+		error 1 "Missing ${profilename}/specialize/specialize.ps1 file for profile ${bldylw}${profilename}${txtrst}"
+		exit 1
+	fi
+
+
+	if [ ! -e "${profilename}/specialize/tools.csv" ];
+	then
+		error 1 "Missing ${profilename}/specialize/tools.csv file for profile ${bldylw}${profilename}${txtrst}"
+		exit 1
+	fi
+
+}
+
+
+# goes trough all defined profiles and validates each of them
+function validate_profiles()
+{
+	local profile
+
+	for profile in $profiles;
+	do
+		# validate each profile if its name is not empty
+		[ ! -z "$profile" ] && validate_profile $profile
+	done
 }
 
 
@@ -423,29 +592,29 @@ function run()
 function run_virtualbox()
 {
 
-	if [ -e ~/workspace/win-image-builder/vbox/${vmname}/${vmname}.vdi ]
+	if [ -e ${vmpath}/vbox/${vmname}/${vmname}.vdi ]
 	then
-		info 2 "unregister & delete harddisk"
-		vboxmanage closemedium disk ~/workspace/win-image-builder/vbox/${vmname}/${vmname}.vdi --delete
+		info 2 "Unregister & delete harddisk"
+		vboxmanage closemedium disk ${vmpath}/vbox/${vmname}/${vmname}.vdi --delete
 	fi
 
 	info 3 "Create VM and register with VirtualBox"
-	run 2 VBoxManage createvm --name ${vmname} --register --ostype Windows2012_64 --basefolder ~/workspace/win-image-builder/vbox
+	run 2 VBoxManage createvm --name ${vmname} --register --ostype Windows2012_64 --basefolder ${vmpath}/vbox
 
 	info 3 "Create disk"
-	run 2 VBoxManage createhd --filename ~/workspace/win-image-builder/vbox/${vmname}/${vmname}.vdi --size 25000 --variant standard
+	run 2 VBoxManage createhd --filename ${vmpath}/vbox/${vmname}/${vmname}.vdi --size 25000 --variant standard
 
 	info 3 "Create storage controller (for disk & CDROM)"
 	run 2 VBoxManage storagectl ${vmname} --name "IDE" --add ide --controller PIIX4
 
 	info 3 "Attach disk"
-	run 2 VBoxManage storageattach ${vmname} --storagectl "IDE" --port 0 --device 1 --type hdd --medium  ~/workspace/win-image-builder/vbox/${vmname}/${vmname}.vdi
+	run 2 VBoxManage storageattach ${vmname} --storagectl "IDE" --port 0 --device 1 --type hdd --medium  ${vmpath}/vbox/${vmname}/${vmname}.vdi
 
 	info 3 "Create floppy controller"
 	run 2 VBoxManage storagectl ${vmname} --name "Floppy" --add floppy
 
 	info 3 "Attach unattend.img to floppy controller"
-	run 2 VBoxManage storageattach ${vmname} --storagectl "Floppy" --port 0 --device 0 --type fdd --medium ~/workspace/win-image-builder/input/unattend.img
+	run 2 VBoxManage storageattach ${vmname} --storagectl "Floppy" --port 0 --device 0 --type fdd --medium ${vmpath}/unattend.img
 
 	info 3 "Create storage controller (for disk & CDROM)"
 	run 2 VBoxManage storagectl ${vmname} --name "SATA" --add sata --controller IntelAHCI --portcount 4
@@ -455,14 +624,15 @@ function run_virtualbox()
 	run 2 VBoxManage storageattach ${vmname} --storagectl "SATA" --port 1 --type dvddrive --medium ${builder_iso}
 	run 2 VBoxManage storageattach ${vmname} --storagectl "SATA" --port 2 --type dvddrive --medium ${virtio_iso}
 
-	run 2 VBoxManage sharedfolder add ${vmname} --name output --hostpath ~/workspace/win-image-builder/output --automount
+	run 2 VBoxManage sharedfolder add ${vmname} --name output --hostpath ${vmpath}/output --automount
 
-	run 2 VBoxManage modifyvm ${vmname} --boot1 disk
-	run 2 VBoxManage modifyvm ${vmname} --boot2 dvd
+	run 2 VBoxManage modifyvm ${vmname} --boot1 dvd
+	run 2 VBoxManage modifyvm ${vmname} --boot2 disk
 	run 2 VBoxManage modifyvm ${vmname} --boot3 none
 	run 2 VBoxManage modifyvm ${vmname} --boot4 none
 
-	run 2 VBoxManage modifyvm ${vmname} --nic1 bridged --cableconnected1 on --bridgeadapter1 en0
+	info 3 "Bridging eth0 to the virtual machine's network adapter"
+	run 2 VBoxManage modifyvm ${vmname} --nic1 bridged --cableconnected1 on --bridgeadapter1 ${bridgeadapter}
 	run 2 VBoxManage modifyvm ${vmname} --memory 4096
 	run 2 VBoxManage modifyvm ${vmname} --clipboard bidirectional
 
@@ -474,8 +644,10 @@ function run_virtualbox()
 
 parse_parameters $*
 set_colors
+get_os
 validate_environment_vars
 validate_net_connectivity
 validate_prerequisites
-get_os
+validate_profiles
+#run_virtualbox
 
